name: Build APK with Buildozer

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip python3-setuptools python3-wheel python3-cffi python3-virtualenv libffi-dev libssl-dev libsqlite3-dev zlib1g-dev libjpeg-dev libfreetype6-dev pkg-config libgl1-mesa-dev libgles2-mesa-dev
        pip install --upgrade pip
        pip install buildozer cython

    - name: Build APK (trigger SDK download)
      run: buildozer android debug || true

    - name: Accept Android SDK licenses
      run: |
        yes | ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses || true
        yes | ~/.buildozer/android/platform/android-sdk/cmdline-tools/bin/sdkmanager --licenses || true
        yes | ~/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager --licenses || true

    - name: Build APK (real)
      run: buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: my-app-apk
        path: bin/*.apk
